name:                formula-evaluator
version:             0.1.0.0
synopsis: "Simple extensible formula parser and evaluator (with REPL)"
github:              "pier-bezuhoff/formula-evaluator"
license:             BSD3
author:              "Pier Bezuhov"
maintainer:          "pierbezuhoff2016@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pier-bezuhoff/formula-evaluator#readme>

dependencies:
- base >= 4.7 && < 5
- containers # Data.Map
- mtl
- template-haskell
- list-t # also there is ListT

library:
  source-dirs: src

executables:
  formula-evaluator-exe:
    main:                Main.hs
    other-modules: []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formula-evaluator
  formula-evaluator-repl-exe:
    main: REPL.hs
    other-modules: []
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formula-evaluator

tests:
  formula-evaluator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - formula-evaluator
